hashtags = [
    '#TrendingNow #StartupLife #EntrepreneurMindset',
    '#SuccessStories #TechTuesday #AI ',
    '#AI #Innovations #CyberTalk',
    '#CyberTalk #DigitalTools #TechSavvy',
    '#TechNews #Education #Learning',
    '#Learning #PersonalDevelopment #GrowthMindset',
    '#StudyTips #SelfImprovement #Motivation',
    '#CareerDevelopment #LifelongLearning #SuccessTips',
    '#PassiveIncome #PurposeDriven #MondayMotivation',
    '#GoalSetting #SuccessMindset #DailyInspiration',
    '#KeepPushing #PositiveVibes #DreamBig',
    '#StayFocused #StayPositive',
    
    "#TrendingNow #StartupLife",
    "#TrendingNow #EntrepreneurMindset",
    "#TrendingNow #AI",
    "#TrendingNow #TechNews",
    "#TrendingNow #Learning",

    "#StartupLife #EntrepreneurMindset",
    "#StartupLife #SuccessStories",
    "#StartupLife #TechTuesday",
    "#StartupLife #AI",
    "#StartupLife #Innovations",

    "#EntrepreneurMindset #GrowthMindset",
    "#EntrepreneurMindset #Motivation",
    "#EntrepreneurMindset #GoalSetting",
    "#EntrepreneurMindset #SuccessTips",
    "#EntrepreneurMindset #DailyInspiration",

    "#SuccessStories #TechTuesday",
    "#SuccessStories #CareerDevelopment",
    "#SuccessStories #LifelongLearning",
    "#SuccessStories #DreamBig",
    "#SuccessStories #Motivation",

    "#AI #Innovations",
    "#AI #CyberTalk",
    "#AI #MachineLearning",
    "#AI #Automation",
    "#AI #TechSavvy",

    "#CyberTalk #DigitalTools",
    "#CyberTalk #Linux",
    "#CyberTalk #Automation",
    "#CyberTalk #TechNews",
    "#CyberTalk #OpenSource",

    "#Learning #PersonalDevelopment",
    "#Learning #GrowthMindset",
    "#Learning #StudyTips",
    "#Learning #SelfImprovement",
    "#Learning #CareerDevelopment",

    "#CareerDevelopment #LifelongLearning",
    "#CareerDevelopment #SuccessTips",
    "#CareerDevelopment #Job",
    "#CareerDevelopment #Hiring",
    "#CareerDevelopment #Internship",

    "#PassiveIncome #MondayMotivation",
    "#PassiveIncome #GoalSetting",
    "#PassiveIncome #PurposeDriven",
    "#PassiveIncome #SuccessMindset",
    "#PassiveIncome #DailyInspiration",

    "#Python #MachineLearning",
    "#Python #Automation",
    "#Python #Linux",
    "#Python #Hackathon",
    "#Python #Internship",

    "#Java #Backend",
    "#Java #CareerDevelopment",
    "#Java #Hiring",
    "#Java #Enterprise",
    "#Java #Coding",

    "#JavaScript #WebDevelopment",
    "#JavaScript #Node",
    "#JavaScript #React",
    "#JavaScript #Frontend",
    "#JavaScript #Programming",

    "#C #Programming",
    "#CPP #Coding",
    "#Ruby #WebDev",
    "#SQL #Databases",
    "#HTML #CSS",

    "#AI #Python #MachineLearning",
    "#AI #Automation #TechSavvy",
    "#AI #Innovations #TechNews",
    "#AI #CyberTalk #DigitalTools",

    "#StartupLife #AI #Innovations",
    "#StartupLife #Tech #Automation",
    "#StartupLife #GrowthMindset #Success",

    "#Learning #Motivation #GrowthMindset",
    "#Learning #StudyTips #SelfImprovement",
    "#Learning #CareerDevelopment #Success",

    "#Python #Coding #Developers",
    "#Python #Automation #Productivity",
    "#Python #OpenSource #Linux",

    "#CyberTalk #Security #Linux",
    "#CyberTalk #Automation #AI",
    "#CyberTalk #Tech #Developers",

    "#GoalSetting #SuccessMindset #Motivation",
    "#GoalSetting #DailyInspiration #DreamBig",
    "#GoalSetting #GrowthMindset #Focus",

    "#Hackathon #Developers #Coding",
    "#Hackathon #Innovation #Tech",
    "#Hackathon #Learning #Experience",

    "#Internship #Hiring #Job",
    "#Internship #Career #Learning",
    "#Internship #Developers #Growth",

    "#Tech #Innovation #Future",
    "#Tech #Learning #Education",
    "#Tech #Developers #Community",

    "#Automation #Productivity #Tech",
    "#Automation #Python #AI",
    "#Automation #Workflow #Efficiency",

    "#Linux #OpenSource #Developers",
    "#Linux #Tech #Programming",
    "#Linux #Security #CyberTalk"
]


advices = [
    "Hot take: Consistency beats talent in programming every single time.",
    "If you wait to feel ready, you’ll never ship anything.",
    "Your first version should embarrass you. That’s how you know you started early.",
    "Stop optimizing code that no one is using yet.",
    "The fastest way to learn is to break things and fix them yourself.",
    "Copying code is fine. Not understanding it is the problem.",
    "Real confidence comes from solving bugs alone at 2 AM.",
    "Frameworks change. Problem-solving doesn’t.",
    "You’re not bad at coding—you’re just inexperienced.",
    "If it feels slow, you’re probably learning something important.",
    "Reading docs feels boring until you realize they answer everything.",
    "Side projects matter more than certificates.",
    "If your app has no users, performance doesn’t matter.",
    "You don’t need to know everything. You need to know how to find answers.",
    "Coding every day for 30 minutes beats coding once a week for 5 hours.",
    "The best developers Google things constantly.",
    "If debugging feels frustrating, you’re doing real work.",
    "Clean code comes after ugly working code.",
    "Don’t chase trends. Chase fundamentals.",
    "Most bugs are logic errors, not syntax errors.",
    "You learn more by finishing a bad project than abandoning a perfect idea.",
    "Version control is not optional. Learn Git early.",
    "If you can explain your code simply, you understand it.",
    "Your code will suck at first. That’s normal.",
    "Stop comparing your chapter 1 to someone else’s chapter 10.",
    "Programming rewards patience more than intelligence.",
    "Build boring projects. They teach real-world skills.",
    "You don’t need a startup idea to be a good developer.",
    "The terminal is scary until it becomes your best friend.",
    "Errors are not failures. They’re instructions.",
    "Refactoring is easier when your code actually exists.",
    "You can’t optimize what you don’t understand.",
    "Learning to read code is as important as writing it.",
    "The hardest part of coding is starting.",
    "Ship small, break small, fix fast.",
    "Your portfolio speaks louder than your resume.",
    "Being stuck means you’re close to learning something new.",
    "Code reviews hurt because they work.",
    "If you hate debugging, you probably don’t understand the problem yet.",
    "Most “overnight success” devs coded for years quietly.",
    "Writing tests feels slow until they save you hours.",
    "The best skill is knowing what not to build.",
    "Don’t memorize syntax. Understand concepts.",
    "Your future self will thank you for comments.",
    "Bad variable names cause more bugs than bad logic.",
    "If everything makes sense, you’re not challenging yourself.",
    "Programming is thinking, typing is secondary.",
    "You don’t need permission to build something useful.",
    "Learn one language deeply before chasing the next.",
    "If your code works, you’re already ahead of most beginners.",
    "Bugs don’t mean you’re dumb. They mean you’re human.",
    "Focus on finishing, not perfection.",
    "Real learning happens outside tutorials.",
    "The best projects solve your own problems first.",
    "If you can debug, you can survive any tech stack.",
    "Reading stack traces is a superpower.",
    "Don’t fear legacy code. Learn from it.",
    "Code is communication, not just instructions.",
    "If it feels hard, good—you’re leveling up.",
    "You’ll learn more from one failed project than ten ideas.",
    "The compiler is strict because it’s honest.",
    "Writing bad code is part of writing good code.",
    "Stop overthinking tools and start building.",
    "Your first solution doesn’t need to be optimal.",
    "Every bug fixed increases your confidence.",
    "If you’re confused, you’re on the right track.",
    "Coding rewards those who don’t quit.",
    "Understanding why something failed is real progress.",
    "You don’t need motivation when you have discipline.",
    "Your skills grow when your comfort zone shrinks.",
    "Most problems are simpler than they look.",
    "Reading other people’s code makes you better fast.",
    "Don’t rewrite everything. Fix what matters.",
    "Your job is to solve problems, not impress compilers.",
    "If your project works, celebrate—even if the code is messy.",
    "Every expert was once stuck on basics.",
    "You learn faster by doing than by watching.",
    "If you’re debugging, you’re building skill.",
    "Good developers finish things.",
    "The best way to learn architecture is to break it.",
    "Code first. Optimize later.",
    "If it runs, you did something right.",
    "The gap between you and experts is just time and effort.",
    "Programming is hard—that’s why it’s valuable.",
    "If you understand the problem clearly, the code becomes obvious.",
    "Most timeouts are caused by overthinking, not bad hardware.",
    "Your brain learns faster when you struggle a little.",
    "Writing pseudocode saves more time than typing faster.",
    "If you can’t break your own app, users will.",
    "Good developers ask better questions, not more questions.",
    "You don’t need a roadmap—just the next small step.",
    "Coding late teaches you discipline, not magic.",
    "If your solution is simple, you probably understood the problem.",
    "Every crash is feedback, not a personal attack.",
    "The best refactor is sometimes deleting code.",
    "If you’re stuck, explain the problem out loud.",
    "Understanding data flow matters more than syntax tricks.",
    "Your debugger is smarter than guesswork—use it.",
    "Writing logs is cheaper than guessing bugs.",
    "Most features don’t fail because of code, but because of assumptions.",
    "If you fear touching code, you waited too long to refactor.",
    "Clarity beats cleverness in production code.",
    "You don’t learn architecture from diagrams alone.",
    "Good code is predictable, not impressive.",
    "If your code is hard to explain, it’s hard to maintain.",
    "Constraints make you a better programmer.",
    "The fastest fix is often the simplest one.",
    "Every time you read docs, you save future debugging time.",
    "Programming is less about answers and more about trade-offs.",
    "If your code surprises you, it will surprise others too.",
    "Most bugs hide in edge cases you ignored.",
    "Naming things well is half the problem solved.",
    "If it works locally, test it somewhere else.",
    "Assume your code will be read by tired humans.",
    "Simple solutions scale better than clever hacks.",
    "You grow faster when you finish uncomfortable tasks.",
    "The best learning happens when nothing works.",
    "Code that’s easy to change is better than code that’s fast.",
    "You don’t need more features, you need fewer bugs.",
    "Understanding basics makes advanced topics trivial.",
    "If your codebase scares you, clean one file today.",
    "Programming is debugging with extra steps.",
    "If you can reproduce a bug, you can fix it.",
    "Good defaults prevent future mistakes.",
    "Your first instinct is rarely the best solution.",
    "Working code teaches faster than theoretical perfection.",
    "If you feel slow, you’re probably doing it right.",
    "The best engineers think in systems, not files.",
    "Learning never ends—comfort is the real enemy.",
    "If your logic is solid, syntax errors are easy.",
    "Don’t trust inputs, not even your own.",
    "Code reviews are about clarity, not ego.",
    "Your future bugs are written today.",
    "A small improvement every day compounds fast.",
    "If your fix adds complexity, rethink it.",
    "Understanding failure cases makes you dangerous—in a good way.",
    "Don’t guess performance. Measure it.",
    "Most crashes happen where you felt confident.",
    "Readable code outlives smart code.",
    "You learn more fixing bugs than adding features.",
    "If everything works instantly, you missed something.",
    "The best skill is staying calm when nothing works.",
    "Every warning ignored becomes a future error.",
    "Code that’s easy to test is easy to trust.",
    "You don’t need speed—you need correctness first.",
    "Hard bugs make strong developers.",
    "If your code depends on luck, it’s broken.",
    "Understanding constraints unlocks creativity.",
    "Programming rewards curiosity more than memory.",
    "If you solved it once, write it down.",
    "Your job is to reduce uncertainty.",
    "Good software fails gracefully.",
    "The simplest bug fixes teach the biggest lessons.",
    "If you can’t explain the bug, you can’t fix it.",
    "Better error messages save developer lives.",
    "If your app survives bad input, it’s growing up.",
    "Programming is learning to think clearly under pressure.",
    "The best tools amplify understanding, not replace it.",
    "You don’t need genius—just persistence.",
    "If it’s hard to debug, it’s hard to maintain.",
    "Every solved problem sharpens your intuition.",
    "Code doesn’t lie—assumptions do.",
    "The best fixes remove causes, not symptoms.",
    "If you respect edge cases, production will respect you.",
    "Programming mastery is built one bug at a time.",
    "Your confidence grows every time you don’t quit.",
    "Clear thinking produces clean code.",
    "If your solution feels calm, it’s probably right.",
    '''Advice for programmers:
    "Logs > guessing."

    If you can’t explain what your system is doing,
    you don’t control it.
    '''
]